name: Build LaTeX documents
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Report.tex
          latexmk_shell_escape: true
          work_in_root_file_dir: true
      - name: Upload as artifact - all commits
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: '**/*.pdf'
      - name: Upload as release - only tagged commits
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '**/*.pdf'